### ISSUE TITLE
[UserStory] Compare Maven, Gradle, and Ant for use in this project

### ISSUE THREAD

**Issue by ccason1** [MetroCS/QualityToolsForBlueJ#13]
# User Story
### Essential components
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a maintainer
I want a comparison of Maven, Gradle, and Ant
so that a build environment can be established per User Story #2

## Acceptance Criteria

* A comparison of relevant characteristics of Maven, Gradle, and Ant exists in the repository
* The comparison lists reasons why each build tool would be appropriate and/or inappropriate for this specific project
* The comparison uses insights from and expands upon User Story #4 
* The comparison cites authoritative references

## Issues Dependent on This User Story

* User Story #2
* User Story #4

**Comment by jody** [comment]
"developer" is not one of the identified **stakeholder groups**.

This sounds like there's useful activity associated with this, but it doesn't explain or describe what comprises "an evaluation".  The acceptance criteria is likewise vague.  It also refers to some "comparison"; but the story itself only refers to a single tool... so it is unclear _what_  is being compared to _what else_.  It is likewise unclear how completing this user story results in establishing a build environment.

Please edit this to clarify the intent, outcome, and how completion is measured/determined.

**Comment by jody** [comment]
"contributor" is not an identified **stakeholder**.  (See: Vision statement)  Assuming "maintainer" is desired stakeholder type.

The rationale seems to presume that only Maven is being considered or that Maven is the only tool that will address the goal of establishing a build environment.  Why is that the case?

Since decision-making is best based on a _comparison_ of tools, it would be useful for this effort to provide _comparative_ information.

Given that Ant and Gradle information now exists, a more useful user story might be to **provide a comparison of Ant, Gradle, and Maven.**  The effort could draw upon the information already provided for Ant and Gradle.

**Comment by jody** [comment]
Resolved by #53.
