### ISSUE TITLE
[UserStory] Provide a list of tools to be integrated with a brief description of each one

### ISSUE THREAD

**Issue by alope151** [MetroCS/QualityToolsForBlueJ#14]
# User Story
### Essential components
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a  maintainer  
I want to have a list of tools that stakeholders currently would like to be integrated and their descriptions/informative links  
so that I can understand which tools the extension may be expected to integrate.

## Acceptance Criteria
Rules or scenarios are acceptable formats.

* A well-labeled list of the tools exists in the repository.
* The list includes a brief description of the intent of each tool.
* The list includes a link to each tool's home page.

## Supporting Information
As a first time contributor (maintainer) I was not too sure what tools were needed in the extension. Adding this information to the repository makes it more accessible to newcomers.

**Comment by jody** [comment]
This looks good overall.

Please change "existing list of the tools that will be integrated" to "list of tools that stakeholders currently would like to be integrated".  Note that the list contents are expected to be dynamic, with the list changing over time.  Likewise change "full list" in the acceptance criteria.

It's unclear how this will "guarantee" "full understanding", so that's probably too strong.  It seems that the objective is to permit maintainers to know what tools still need to be integrated.

**Comment by holsappled** [comment]
CraftCoders would like to be assigned this user story.

@holsappled 
@AhmedSamay  
@SerenaWhite 
@shadycloud

**Comment by shadycloud** [comment]
This user story is satisfied by [this document](https://github.com/MetroCS/QualityToolsForBlueJ/blob/master/toolsForIntegration.md) which includes a well-labeled list of the tools, brief description of the intent of each tool, and a link to each tool's home page.  ( Eric + Ren )
