### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by HariShrestha** [MetroCS/QualityToolsForBlueJ#24]
# User Story
As a student
I want all my projects show  on the left side of the blue j so that I can open any previous project without wasting my time.
### Essential components
- [ ] Issue title describes the user story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a  _stakeholder type_
I want  _desired outcome_
so that  _stakeholder value rationale_

## Acceptance Criteria
Rules or scenarios are acceptable formats.

* _Rule 1_
* _Rule 2_
* _Rule 3_

**Scenario 1**
Given  _initial state or conditions_
when  _event or action_
then  _specified outcome_

**Comment by jody** [comment]
This appears to be a **Design** specification rather than a **Requirement** specification.  This is because it states *how* a feature should be implemented rather than *what* the feature is.

This particular story is also outside the scope of the _Quality Tools for BlueJ_ project in that it doesn't address an aspect of integrating quality assessment tools in a BlueJ extension.  It appears to be potentially relevant to the BlueJ product itself, so you may wish to make a recommendation to BlueJ product developers. 

Note also that the format of this issue submission doesn't match or make use of the template.  See other accepted user stories for examples (such as #4).

For each of these reasons, this issue is being closed.
