### ISSUE TITLE
[UserStory] Menu for configuring code analysis tools

### ISSUE THREAD

**Issue by jstrelka** [MetroCS/QualityToolsForBlueJ#49]
# User Story
### Essential components
- [ ] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a** user
**I want** a gui for configuring any tools that are extensions of BlueJ
**so that** I can configure any code analysis tool to my preferences.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* Each tool should have its own menu
* Menu options should correlate to the tools configuration options
* Menus should allow users to upload any pre-existing configuration file

### Scenario 1
**Given** a configuration menu 
**when** working with a new tool 
**then** I can create my own configurations

## Supporting Information
None.

### Depends On
Getting various tools plugged-in to BlueJ through a .jar file.

**Comment by jody** [comment]
The **Story** itself seems OK.

The **Acceptance Criteria**, however, specifies only one way of achieving the result and is thus a "Design Specification" rather than a general way of verifying the user story.  For example, this user story can only be satisfied by providing a menu.  Other user interface elements might be just as or more appropriate (e.g., use of panels in the Extensions tab of the Preferences dialog).

**Depends On** should include references to other issues that this story needs in order to be completed.

**Comment by shadycloud** [comment]
I would like to see check boxes that can toggle each tool on/off in this menu.

**Comment by jody** [comment]
"Check boxes" is likewise a design and implementation decision that should be left up to the UI designer/developer.

Personally, I would like to see sliders that show how aggressive a tool should be in its analysis and reporting.  It's very discouraging to be faced with over a hundred errors in a Checkstyle report of a 25-line program.

**Comment by jstrelka** [comment]
Opened new issue #74 with revised "Acceptance Criteria" and "Title"
